### ISSUE TITLE
Sending to CC/IC from Blender issues

### ISSUE THREAD

**Issue by cuddlyogre** [soupday/CCiC-Blender-Pipeline-Plugin#36]
I don't know if this is a CCIC issue, or a Blender issue.

The character was exported from CC using the CC/iClone Blender Pipeline v2.0.8 with the default settings. CC/iClone Blender Pipeline Plugin in CC/IC is 2.0.8b

When sending poses and animations to CC/IC from Blender, not everything makes it. Whether or not the character has been rigified doesn't seem to matter.

This pose was sent from CC to Blender without a problem, but when I send it back, the leg translations don't make it.

Blender pose
![00](https://github.com/soupday/CCiC-Blender-Pipeline-Plugin/assets/3506795/50fc7aac-b423-4b83-b0a5-29a73fce01e0)
![04](https://github.com/soupday/CCiC-Blender-Pipeline-Plugin/assets/3506795/260e65e9-a15a-4922-a8a6-75b82f8a5d97)

In CC, but also happens in IC
![01](https://github.com/soupday/CCiC-Blender-Pipeline-Plugin/assets/3506795/4cb4ea24-4cbc-4280-851d-337e09d643a6)
![05](https://github.com/soupday/CCiC-Blender-Pipeline-Plugin/assets/3506795/f5410124-b73c-4dfe-bc2c-b87732919212)

When sending poses from CC to Blender and you're using Rigify, this happens:
![06](https://github.com/soupday/CCiC-Blender-Pipeline-Plugin/assets/3506795/581dc18c-277b-4b6b-b9ea-6e3879f087a2)
![07](https://github.com/soupday/CCiC-Blender-Pipeline-Plugin/assets/3506795/23ce7ce8-5e34-49b4-a95c-c8b708fa21dd)

Exporting a motion with rigify is also having troubles. Using the default skeleton exports and imports without a problem.
End pose in Blender:
![image](https://github.com/soupday/CCiC-Blender-Pipeline-Plugin/assets/3506795/554878fd-b975-4c96-87c0-0bdf1fe6d994)

End pose in CC
![image](https://github.com/soupday/CCiC-Blender-Pipeline-Plugin/assets/3506795/a0c9adc8-e795-436f-919f-e2ab6352d4db)

If I don't uncheck select root bone, this happens:
![image](https://github.com/soupday/CCiC-Blender-Pipeline-Plugin/assets/3506795/46b1639f-71bd-4a30-b377-54b75d9b8ce1)

I couldn't recreate it here, but sometimes the RibsTwist bones import incorrectly, causing odd placement and scaling.

**Comment by soupday** [comment]
What method are you using to export back to CC4?

**Comment by cuddlyogre** [comment]
I'm sorry, I forgot that important bit. It's the data link tools that are giving me trouble. Traditional import/export are working perfectly.

**Comment by cuddlyogre** [comment]
An update. When exporting an animation from a non-rigified avatar, the animation doesn't seem to carry over. I've tried with and without importing the profile. When exporting an animation through Export > FBX, the animation imports without issue.

**Comment by cuddlyogre** [comment]
When you send a pose from CC to Blender with a rigified avatar and it turns it into the butterfly demon looking thing, the bones in the skeleton are all individually scaled way down.

**Comment by cuddlyogre** [comment]
More update: The culprit for the butterfly demon bug is at write_sequence_actions when you set the f curve values. It appears that somewhere a scaling number isn't being applied properly and all the bones are being scaled down, my guess is by 100x, since that is the scale of the avatar mesh when it is imported.

**Comment by soupday** [comment]
Yeah, the rigify rig bones are at world units scale (1 unit = 1m) wheres everything from CC/iC is 1 unit = 1cm. It was in fact decode_pose_frame_data() setting the wrong armature scale.

Should be fixed in [2.0.9](https://github.com/soupday/CCiC-Blender-Pipeline-Plugin/tree/2.0.9). All the datalink animation transfer functionality should work, and it should go a lot faster now.

The foot problem in CC4 is due to the foot IK being permanently locked. The latest version CC 4.42.3004.1 released a few days ago fixed this.

**Comment by cuddlyogre** [comment]
Awesome. I'll check it out and let you know. I appreciate the work you've done on this!

**Comment by soupday** [comment]
And... I've just realised that iClone doesn't yet have the new API functions to correct the facial expression bone rotations, which is probably why it all went wrong in iClone too. 

I've updated the [2.0.9 plug-in](https://github.com/soupday/CCiC-Blender-Pipeline-Plugin/releases/tag/2.0.9) for CC4/iClone, so you'll probably need to get that again.
